// Synthetic Demonstration Data — no real Oil India information is used.
import type {
  Activity,
  Conflict,
  CrossLink,
  Discipline,
  MemoryRecord,
  SiteReport,
  Unmatched,
  AuditLog,
} from "./types";
import { TODAY, addDays } from "./dates";

export const PROJECT = {
  id: "OIL-REF-2026-01",
  name: "Refinery Expansion & Utilities Project",
  status: "In Progress",
  client: "Oil India Limited (demonstration)",
  location: "Synthetic Site — Upper Assam",
  baseline: "BL-03 (approved 12 Jan 2026)",
  start: "2026-01-15",
  finish: "2027-06-30",
  dataLabel: "Synthetic Demonstration Data",
};

export const DISCIPLINES: Discipline[] = [
  "Civil",
  "Piping",
  "Mechanical",
  "Rotating",
  "Electrical",
  "Instrumentation",
  "HSE",
];

export const AREAS: Record<string, string> = {
  "Area A": "Crude Distillation Unit",
  "Area B": "Diesel Hydrotreater",
  "Area C": "Utilities & Offsites",
};

export const CONTRACTORS: Record<Discipline, string> = {
  Civil: "Brahmaputra Civil Works",
  Piping: "Assam Pipeline Constructors",
  Mechanical: "Northeast Mech Erectors",
  Rotating: "Kaziranga Rotating Services",
  Electrical: "Digboi Electricals Pvt Ltd",
  Instrumentation: "Tezpur Instrumentation Co.",
  HSE: "Site HSE Cell",
};

const DCODE: Record<Discipline, string> = {
  Civil: "CIV",
  Piping: "PIP",
  Mechanical: "MEC",
  Rotating: "ROT",
  Electrical: "ELE",
  Instrumentation: "INS",
  HSE: "HSE",
};

type Row = [
  string,
  string,
  Discipline,
  string,
  number,
  number,
  "C" | "P" | "D" | "N",
  number,
  number,
  string[]?,
];
// id, name, discipline, area, planned start offset (days from today), duration, state, progress, slip days, deps
const ROWS: Row[] = [
  ["CIV-A-0101", "Site Grading & Compaction Area A", "Civil", "Area A", -60, 10, "C", 100, 1],
  ["CIV-A-0102", "Foundation F-102 Concreting", "Civil", "Area A", -8, 10, "P", 85, 1],
  ["CIV-A-0105", "Pipe Rack PR-1 Foundations", "Civil", "Area A", -45, 14, "C", 100, 2],
  ["CIV-A-0108", "Equipment Foundation F-108", "Civil", "Area A", -30, 12, "C", 100, 0],
  [
    "CIV-A-0110",
    "Anchor Bolt Grouting F-108",
    "Civil",
    "Area A",
    -20,
    4,
    "C",
    100,
    1,
    ["CIV-A-0108"],
  ],
  ["CIV-B-0112", "Pump Foundation P-101 Plinth", "Civil", "Area B", -40, 8, "C", 100, 0],
  ["CIV-B-0118", "Underground Drainage Network", "Civil", "Area B", -12, 20, "D", 30, 5],
  ["CIV-C-0124", "Cable Trench Excavation Unit 2", "Civil", "Area C", -35, 10, "C", 100, 2],
  ["CIV-C-0130", "Road & Paving Utilities Block", "Civil", "Area C", 6, 15, "N", 0, 0],
  [
    "PIP-A-0240",
    "Pipe Rack PR-1 Steel Erection",
    "Piping",
    "Area A",
    -32,
    12,
    "C",
    100,
    1,
    ["CIV-A-0105"],
  ],
  [
    "PIP-A-0245",
    'Erect Line 24"-XX',
    "Piping",
    "Area A",
    -3,
    5,
    "D",
    0,
    0,
    ["PIP-A-0240", "PIP-A-0252"],
  ],
  ["PIP-A-0246", 'Erect Line 18"-YY', "Piping", "Area A", -4, 7, "P", 40, 1, ["PIP-A-0240"]],
  ["PIP-A-0252", "Spool Fabrication Batch 3", "Piping", "Area A", -28, 14, "C", 100, 2],
  ["PIP-A-0258", 'Weld NDT Line 16"-ZZ', "Piping", "Area A", -6, 8, "P", 55, 1],
  [
    "PIP-A-0271",
    "Install Pipe Supports PR-1",
    "Piping",
    "Area A",
    -9,
    12,
    "P",
    60,
    2,
    ["PIP-A-0240"],
  ],
  ["PIP-B-0277", 'Erect Line 12"-HT-04', "Piping", "Area B", -14, 10, "D", 45, 4],
  ["PIP-B-0280", 'Erect Line 8"-PR-07', "Piping", "Area B", -5, 8, "P", 35, 1],
  ["PIP-B-0283", "Hydrotest Loop HT-12", "Piping", "Area B", 4, 5, "N", 0, 0, ["PIP-B-0277"]],
  ["PIP-C-0290", 'Cooling Water Header 30"-CW', "Piping", "Area C", -20, 15, "D", 50, 3],
  ["PIP-C-0294", 'Firewater Line 10"-FW Erection', "Piping", "Area C", -38, 14, "C", 100, 1],
  [
    "MEC-A-0501",
    "Static Equipment Installation V-201",
    "Mechanical",
    "Area A",
    -25,
    10,
    "C",
    100,
    1,
    ["CIV-A-0108"],
  ],
  ["MEC-A-0505", "Heat Exchanger E-204 Setting", "Mechanical", "Area A", -18, 8, "C", 100, 0],
  ["MEC-A-0508", "Column C-101 Internals Installation", "Mechanical", "Area A", -7, 14, "P", 35, 2],
  ["MEC-B-0514", "Storage Tank T-301 Shell Erection", "Mechanical", "Area B", -50, 30, "C", 100, 2],
  ["MEC-B-0518", "Air Cooler AC-3 Setting", "Mechanical", "Area B", -6, 10, "P", 40, 1],
  ["MEC-A-0510", "Pump Installation P-101", "Rotating", "Area B", 1, 6, "N", 0, 0, ["CIV-B-0112"]],
  ["ROT-A-0520", "Compressor K-201 Alignment", "Rotating", "Area A", -10, 10, "D", 20, 5],
  ["ROT-B-0526", "Pump P-102 Grouting", "Rotating", "Area B", -22, 4, "C", 100, 0],
  ["ROT-C-0532", "Cooling Tower Fan CT-1 Installation", "Rotating", "Area C", -9, 12, "P", 70, 0],
  ["ROT-B-0538", "Pump P-103 Coupling Alignment", "Rotating", "Area B", -2, 5, "P", 25, 1],
  ["ELE-A-0308", "Substation SS-2 Earthing Grid", "Electrical", "Area A", -40, 12, "C", 100, 1],
  [
    "ELE-A-0314",
    "Install Cable Tray Unit 2",
    "Electrical",
    "Area A",
    -10,
    14,
    "P",
    65,
    2,
    ["CIV-C-0124"],
  ],
  [
    "ELE-A-0320",
    "Pull Power Cable Unit 2",
    "Electrical",
    "Area A",
    -2,
    10,
    "D",
    0,
    0,
    ["ELE-A-0314", "PIP-A-0245"],
  ],
  ["ELE-B-0326", "Transformer TR-2 Installation", "Electrical", "Area B", -26, 6, "C", 100, 1],
  ["ELE-B-0332", "MCC Panel Erection SS-2", "Electrical", "Area B", -12, 14, "P", 75, 1],
  ["ELE-C-0338", "Area Lighting Utilities Block", "Electrical", "Area C", -5, 10, "P", 30, 0],
  ["ELE-C-0342", "Earthing Utilities Block", "Electrical", "Area C", -28, 8, "C", 100, 0],
  ["INS-A-0408", "Instrument Tray Routing", "Instrumentation", "Area A", -16, 10, "C", 100, 1],
  [
    "INS-A-0415",
    "Install Pressure Transmitter PT-2401",
    "Instrumentation",
    "Area A",
    -4,
    6,
    "P",
    30,
    1,
    ["PIP-A-0245"],
  ],
  [
    "INS-A-0421",
    "Instrument Calibration Batch 1",
    "Instrumentation",
    "Area A",
    3,
    5,
    "N",
    0,
    0,
    ["INS-A-0415"],
  ],
  ["INS-A-0445", "Impulse Line Tubing", "Instrumentation", "Area A", -3, 9, "P", 20, 1],
  [
    "INS-B-0427",
    "Control Valve CV-110 Installation",
    "Instrumentation",
    "Area B",
    -9,
    7,
    "D",
    20,
    4,
  ],
  ["INS-B-0433", "Junction Box Installation", "Instrumentation", "Area B", -20, 8, "C", 100, 0],
  ["INS-C-0439", "Fire & Gas Detector Loop Check", "Instrumentation", "Area C", -6, 10, "P", 45, 0],
  ["HSE-A-0601", "Fire Protection Inspection", "HSE", "Area A", -14, 3, "C", 100, 0],
  ["HSE-A-0605", "Scaffolding Safety Audit Area A", "HSE", "Area A", -2, 4, "P", 50, 0],
  ["HSE-B-0610", "Confined Space Permit Drill", "HSE", "Area B", -30, 2, "C", 100, 0],
  ["HSE-C-0615", "Fire Water Network Flush", "HSE", "Area C", -18, 7, "C", 100, 1],
];

export const UNITS: Record<string, string> = {
  "Area A": "U2 – Crude Unit Construction",
  "Area B": "U3 – Hydrotreater Construction",
  "Area C": "U4 – Utilities Construction",
};

export function buildActivities(): Activity[] {
  return ROWS.map(([id, name, discipline, area, off, dur, st, prog, slip, deps], i) => {
    const plannedStart = addDays(TODAY, off);
    const plannedFinish = addDays(plannedStart, dur);
    let actualStart: string | null = null;
    let actualFinish: string | null = null;
    if (st === "C") {
      actualStart = addDays(plannedStart, slip);
      actualFinish = addDays(plannedFinish, slip + (i % 2));
    } else if (st === "P" || (st === "D" && prog > 0)) {
      actualStart = addDays(plannedStart, Math.min(slip, -off));
    }
    return {
      id,
      name,
      level: i % 3 === 0 ? "L6" : "L5",
      wbs: `OIL-REF.${UNITS[area]!.slice(0, 2)}.${area.slice(-1)}.${DCODE[discipline]}`,
      unit: UNITS[area]!,
      discipline,
      area,
      plannedStart,
      plannedFinish,
      duration: dur,
      actualStart,
      actualFinish,
      progress: prog,
      dependencies: deps ?? [],
      contractor: CONTRACTORS[discipline],
      verification: st === "N" ? "System Recorded" : "Planner Verified",
      aiConfidence: st === "N" || prog === 0 ? null : 88 + (i % 10),
    };
  });
}

export const DEMO_REPORTS: Record<
  "daily" | "sheet" | "diary",
  Omit<SiteReport, "id" | "status">
> = {
  daily: {
    name: "DPR_028_Area-A-B_28Sep2026.pdf",
    type: "Daily Progress Report",
    fileType: "PDF",
    source: "Daily Progress Report #028",
    date: TODAY,
    discipline: "Multi-discipline",
    lines: [
      "24 inch spool erection started in Area A today at 09:30.",
      "Foundation F102 concreting completed yesterday.",
      "Pipe supports for rack PR-1 installed about 75 percent.",
      "Cable tray Unit 2 installation reached 80 percent.",
      "Pressure transmitter PT-2401 mounted, 50% complete.",
      "Column C-101 internals tray installation progressing, 45%.",
      "Temporary bypass pipe installed near P-101 suction.",
      "18 inch line YY erection progressed to 55% in Area A.",
      "Compressor K-201 alignment works resumed, 30% done.",
      "MCC panel erection in substation SS-2 completed.",
      "Scaffold inspection completed Area A.",
      "Hydrotest pump mobilised for loop HT-12.",
    ],
  },
  sheet: {
    name: "Discipline_Progress_Wk39.xlsx",
    type: "Excel / CSV",
    fileType: "XLSX",
    source: "Discipline Tracker Wk39",
    date: TODAY,
    discipline: "Electrical / Instrumentation / Mechanical",
    lines: [
      "Fire and gas detector loop check Area C 60%",
      "Cooling tower fan CT-1 installation 80%",
      "Air cooler AC-3 setting Area B 55%",
      "Underground drainage network Area B 40%",
      "Impulse line tubing Area A 35%",
      "Temporary cable pulling winch foundation cast Area A",
    ],
  },
  diary: {
    name: "SiteDiary_Supervisor_RK_28Sep.docx",
    type: "Site Diary",
    fileType: "DOCX",
    source: "Supervisor Site Diary 28-Sep",
    date: TODAY,
    discipline: "Piping / Rotating",
    lines: [
      "Pump P-103 coupling alignment reached 50 percent in Area B.",
      "8 inch line PR-07 erection at 60% Area B.",
      "Line 16 inch ZZ weld NDT progressed 70%.",
      "Extra manual isolation valve fitted on firewater ring, not in drawing.",
    ],
  },
};

export const SEED_REPORTS: SiteReport[] = [
  {
    id: "RPT-027",
    name: "DPR_027_Area-A-C_27Sep2026.pdf",
    type: "Daily Progress Report",
    fileType: "PDF",
    source: "Daily Progress Report #027",
    date: addDays(TODAY, -1),
    discipline: "Multi-discipline",
    status: "Processed",
    lines: [],
  },
  {
    id: "RPT-026",
    name: "Contractor_APC_Weekly_38.xlsx",
    type: "Contractor Report",
    fileType: "XLSX",
    source: "Assam Pipeline Constructors Weekly #38",
    date: addDays(TODAY, -2),
    discipline: "Piping",
    status: "Processed",
    lines: [],
  },
  {
    id: "RPT-025",
    name: "Schedule_Extract_P6_BL03.csv",
    type: "Schedule Extract",
    fileType: "CSV",
    source: "Primavera P6 Extract",
    date: addDays(TODAY, -3),
    discipline: "All",
    status: "Processed",
    lines: [],
  },
];

export const SEED_UNMATCHED: Unmatched[] = [
  {
    id: "UNM-011",
    text: "Temporary scaffold access platform built near column C-101 for internals work.",
    source: "Daily Progress Report #027",
    date: addDays(TODAY, -1),
    discipline: "Mechanical",
    area: "Area A",
    closest: "MEC-A-0508",
    closestConfidence: 48,
    aiConfidence: 84,
    explanation:
      "Enabling work performed on site that is not represented as a discrete L6 activity.",
    status: "Open",
  },
  {
    id: "UNM-012",
    text: "Additional drain funnel installed at P-102 baseplate per field instruction FI-219.",
    source: "Assam Pipeline Constructors Weekly #38",
    date: addDays(TODAY, -2),
    discipline: "Piping",
    area: "Area B",
    closest: "ROT-B-0526",
    closestConfidence: 41,
    aiConfidence: 79,
    explanation: "Field-instruction scope that appears to have no baseline schedule activity.",
    status: "Open",
  },
];

export const SEED_CONFLICTS: Conflict[] = [
  {
    id: "CON-004",
    activityId: "PIP-B-0277",
    kind: "PROGRESS CONFLICT",
    status: "Open",
    sources: [
      {
        source: "Contractor Daily Report",
        document: "APC_Daily_27Sep.xlsx",
        timestamp: `${addDays(TODAY, -1)} 18:10`,
        progress: 100,
        author: "Assam Pipeline Constructors",
        note: 'Line 12"-HT-04 erection complete, ready for hydrotest.',
      },
      {
        source: "Supervisor Site Diary",
        document: "SiteDiary_Supervisor_RK_27Sep.docx",
        timestamp: `${addDays(TODAY, -1)} 17:45`,
        progress: 70,
        author: "R. Kalita (Site Supervisor)",
        note: "Final two spools pending, bolting incomplete at flange F-7.",
      },
    ],
  },
  {
    id: "CON-005",
    activityId: "ELE-B-0332",
    kind: "STATUS CONFLICT",
    status: "Open",
    sources: [
      {
        source: "Discipline Tracker",
        document: "Discipline_Progress_Wk39.xlsx",
        timestamp: `${addDays(TODAY, -1)} 09:00`,
        progress: 75,
        author: "Electrical Planning Desk",
        note: "MCC panels 6 of 8 erected.",
      },
      {
        source: "Contractor Daily Report",
        document: "DEPL_DPR_27Sep.pdf",
        timestamp: `${addDays(TODAY, -1)} 19:20`,
        progress: 95,
        author: "Digboi Electricals Pvt Ltd",
        note: "All MCC panels erected, glanding in progress.",
      },
    ],
  },
];

export const CROSS_LINKS: CrossLink[] = [
  {
    id: "XD-01",
    title: "Foundation release to cable pulling chain",
    severity: "high",
    chain: [
      { activityId: "CIV-A-0102", state: "Foundation F102 near completion", tone: "ok" },
      { activityId: "PIP-A-0245", state: 'Line 24" erection started late', tone: "warn" },
      { activityId: "ELE-A-0320", state: "Cable pulling blocked — rack occupied", tone: "risk" },
      { activityId: "INS-A-0415", state: "Transmitter hook-up waiting on line", tone: "warn" },
    ],
    insight:
      'Piping erection on PR-1 is occupying the shared rack tier. Electrical cable pulling cannot begin until Line 24" is supported, which may cascade into instrument hook-up.',
  },
  {
    id: "XD-02",
    title: "Pump P-101 installation readiness",
    severity: "medium",
    chain: [
      { activityId: "CIV-B-0112", state: "Plinth complete & cured", tone: "ok" },
      { activityId: "MEC-A-0510", state: "Pump setting planned 29 Sep", tone: "info" },
      { activityId: "PIP-B-0277", state: "Suction line progress disputed", tone: "risk" },
    ],
    insight:
      "Pump P-101 can be set on schedule, but suction piping progress is in conflict between sources (CON-004). Resolve before hook-up is scheduled.",
  },
  {
    id: "XD-03",
    title: "Compressor alignment vs. HSE permits",
    severity: "low",
    chain: [
      { activityId: "HSE-A-0605", state: "Scaffold audit in progress", tone: "info" },
      { activityId: "ROT-A-0520", state: "Alignment resumed after hold", tone: "warn" },
      { activityId: "ELE-A-0314", state: "Tray above K-201 at 65%", tone: "info" },
    ],
    insight:
      "Overhead cable tray work above K-201 overlaps the compressor alignment window. Consider permit sequencing to avoid simultaneous operations.",
  },
];

export const MEMORY: MemoryRecord[] = [
  {
    activityType: "24 inch Pipe Erection",
    discipline: "Piping",
    occurrences: 18,
    plannedAvg: 5.2,
    actualAvg: 6.7,
    causes: [
      { cause: "Material availability", share: 38 },
      { cause: "Crane availability", share: 27 },
      { cause: "Manpower", share: 21 },
      { cause: "Weather", share: 14 },
    ],
    contractor: "Assam Pipeline Constructors",
    location: "Pipe racks, process units",
    previousProjects: ["NRL Expansion 2019", "Duliajan GCS Revamp 2021", "Numaligarh DHDT 2023"],
  },
  {
    activityType: "Static Equipment Installation",
    discipline: "Mechanical",
    occurrences: 26,
    plannedAvg: 8.0,
    actualAvg: 9.1,
    causes: [
      { cause: "Crane availability", share: 41 },
      { cause: "Foundation readiness", share: 29 },
      { cause: "Vendor documentation", share: 18 },
      { cause: "Weather", share: 12 },
    ],
    contractor: "Northeast Mech Erectors",
    location: "Process units",
    previousProjects: ["Duliajan GCS Revamp 2021", "Bongaigaon CDU 2022"],
  },
  {
    activityType: "Pump Installation & Alignment",
    discipline: "Rotating",
    occurrences: 34,
    plannedAvg: 5.5,
    actualAvg: 7.4,
    causes: [
      { cause: "Grouting cure time", share: 33 },
      { cause: "Piping strain rework", share: 31 },
      { cause: "Vendor specialist", share: 22 },
      { cause: "Manpower", share: 14 },
    ],
    contractor: "Kaziranga Rotating Services",
    location: "Pump alleys",
    previousProjects: ["NRL Expansion 2019", "Numaligarh DHDT 2023"],
  },
  {
    activityType: "Equipment Foundation Concreting",
    discipline: "Civil",
    occurrences: 41,
    plannedAvg: 9.0,
    actualAvg: 9.6,
    causes: [
      { cause: "Weather", share: 46 },
      { cause: "Concrete supply", share: 28 },
      { cause: "Rebar inspection", share: 26 },
    ],
    contractor: "Brahmaputra Civil Works",
    location: "All units",
    previousProjects: ["Bongaigaon CDU 2022", "Duliajan GCS Revamp 2021"],
  },
  {
    activityType: "Cable Tray & Power Cable Pulling",
    discipline: "Electrical",
    occurrences: 22,
    plannedAvg: 11.0,
    actualAvg: 13.2,
    causes: [
      { cause: "Rack access (piping clash)", share: 44 },
      { cause: "Cable delivery", share: 30 },
      { cause: "Manpower", share: 26 },
    ],
    contractor: "Digboi Electricals Pvt Ltd",
    location: "Rack tiers, trenches",
    previousProjects: ["NRL Expansion 2019", "Numaligarh DHDT 2023"],
  },
  {
    activityType: "Instrument Installation & Calibration",
    discipline: "Instrumentation",
    occurrences: 29,
    plannedAvg: 6.0,
    actualAvg: 6.8,
    causes: [
      { cause: "Line readiness", share: 40 },
      { cause: "Calibration equipment", share: 25 },
      { cause: "Vendor documentation", share: 35 },
    ],
    contractor: "Tezpur Instrumentation Co.",
    location: "Process units",
    previousProjects: ["Bongaigaon CDU 2022"],
  },
  {
    activityType: "Hydrotest Loop",
    discipline: "Piping",
    occurrences: 15,
    plannedAvg: 4.0,
    actualAvg: 5.6,
    causes: [
      { cause: "Punch list closure", share: 42 },
      { cause: "Water availability", share: 23 },
      { cause: "Test pack documentation", share: 35 },
    ],
    contractor: "Assam Pipeline Constructors",
    location: "All units",
    previousProjects: ["Duliajan GCS Revamp 2021", "Numaligarh DHDT 2023"],
  },
];

export const SEED_AUDIT: AuditLog[] = [
  {
    id: "AUD-0141",
    timestamp: "27 Sep 2026, 06:12 PM",
    source: "Daily Progress Report #027",
    sourceText: "PR-1 pipe support installation continuing, approx 60%.",
    detected: "PROGRESS 60%",
    activityId: "PIP-A-0271",
    confidence: 93,
    field: "Actual Progress",
    previous: "48%",
    next: "60%",
    reviewer: "Project Planner",
    status: "Approved",
  },
  {
    id: "AUD-0140",
    timestamp: "27 Sep 2026, 05:40 PM",
    source: "Daily Progress Report #027",
    sourceText: "Transformer TR-2 installation completed and handed over.",
    detected: "END",
    activityId: "ELE-B-0326",
    confidence: 97,
    field: "Actual Finish",
    previous: "—",
    next: "23 Sep 2026",
    reviewer: "Project Planner",
    status: "Approved",
  },
  {
    id: "AUD-0139",
    timestamp: "27 Sep 2026, 11:05 AM",
    source: "Assam Pipeline Constructors Weekly #38",
    sourceText: "Line 12 HT-04 erection 100%.",
    detected: "END",
    activityId: "PIP-B-0277",
    confidence: 88,
    field: "Actual Finish",
    previous: "—",
    next: "—",
    reviewer: "System",
    status: "Flagged",
  },
  {
    id: "AUD-0138",
    timestamp: "26 Sep 2026, 04:22 PM",
    source: "Supervisor Site Diary 26-Sep",
    sourceText: "K-201 alignment on hold for shim plates.",
    detected: "PROGRESS",
    activityId: "ROT-A-0520",
    confidence: 91,
    field: "Actual Progress",
    previous: "20%",
    next: "20%",
    reviewer: "Project Manager",
    status: "Approved",
  },
];
