/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleAnalyticsRouteImport } from './routes/_console.analytics'
import { Route as ConsoleAuditRouteImport } from './routes/_console.audit'
import { Route as ConsoleConflictsRouteImport } from './routes/_console.conflicts'
import { Route as ConsoleCrossDisciplineRouteImport } from './routes/_console.cross-discipline'
import { Route as ConsoleDashboardRouteImport } from './routes/_console.dashboard'
import { Route as ConsoleExtractionRouteImport } from './routes/_console.extraction'
import { Route as ConsoleIngestRouteImport } from './routes/_console.ingest'
import { Route as ConsoleMatchingRouteImport } from './routes/_console.matching'
import { Route as ConsoleMemoryRouteImport } from './routes/_console.memory'
import { Route as ConsoleProjectRouteImport } from './routes/_console.project'
import { Route as ConsoleReviewRouteImport } from './routes/_console.review'
import { Route as ConsoleRiskRouteImport } from './routes/_console.risk'
import { Route as ConsoleScheduleRouteImport } from './routes/_console.schedule'
import { Route as ConsoleSettingsRouteImport } from './routes/_console.settings'
import { Route as ConsoleTimeAgentRouteImport } from './routes/_console.time-agent'
import { Route as ConsoleUnmatchedRouteImport } from './routes/_console.unmatched'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAnalyticsRoute = ConsoleAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleConflictsRoute = ConsoleConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCrossDisciplineRoute = ConsoleCrossDisciplineRouteImport.update({
  id: '/cross-discipline',
  path: '/cross-discipline',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleExtractionRoute = ConsoleExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIngestRoute = ConsoleIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMatchingRoute = ConsoleMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMemoryRoute = ConsoleMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectRoute = ConsoleProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReviewRoute = ConsoleReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRiskRoute = ConsoleRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleScheduleRoute = ConsoleScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTimeAgentRoute = ConsoleTimeAgentRouteImport.update({
  id: '/time-agent',
  path: '/time-agent',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUnmatchedRoute = ConsoleUnmatchedRouteImport.update({
  id: '/unmatched',
  path: '/unmatched',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof ConsoleAnalyticsRoute
  '/audit': typeof ConsoleAuditRoute
  '/conflicts': typeof ConsoleConflictsRoute
  '/cross-discipline': typeof ConsoleCrossDisciplineRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/extraction': typeof ConsoleExtractionRoute
  '/ingest': typeof ConsoleIngestRoute
  '/matching': typeof ConsoleMatchingRoute
  '/memory': typeof ConsoleMemoryRoute
  '/project': typeof ConsoleProjectRoute
  '/review': typeof ConsoleReviewRoute
  '/risk': typeof ConsoleRiskRoute
  '/schedule': typeof ConsoleScheduleRoute
  '/settings': typeof ConsoleSettingsRoute
  '/time-agent': typeof ConsoleTimeAgentRoute
  '/unmatched': typeof ConsoleUnmatchedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof ConsoleAnalyticsRoute
  '/audit': typeof ConsoleAuditRoute
  '/conflicts': typeof ConsoleConflictsRoute
  '/cross-discipline': typeof ConsoleCrossDisciplineRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/extraction': typeof ConsoleExtractionRoute
  '/ingest': typeof ConsoleIngestRoute
  '/matching': typeof ConsoleMatchingRoute
  '/memory': typeof ConsoleMemoryRoute
  '/project': typeof ConsoleProjectRoute
  '/review': typeof ConsoleReviewRoute
  '/risk': typeof ConsoleRiskRoute
  '/schedule': typeof ConsoleScheduleRoute
  '/settings': typeof ConsoleSettingsRoute
  '/time-agent': typeof ConsoleTimeAgentRoute
  '/unmatched': typeof ConsoleUnmatchedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/analytics': typeof ConsoleAnalyticsRoute
  '/_console/audit': typeof ConsoleAuditRoute
  '/_console/conflicts': typeof ConsoleConflictsRoute
  '/_console/cross-discipline': typeof ConsoleCrossDisciplineRoute
  '/_console/dashboard': typeof ConsoleDashboardRoute
  '/_console/extraction': typeof ConsoleExtractionRoute
  '/_console/ingest': typeof ConsoleIngestRoute
  '/_console/matching': typeof ConsoleMatchingRoute
  '/_console/memory': typeof ConsoleMemoryRoute
  '/_console/project': typeof ConsoleProjectRoute
  '/_console/review': typeof ConsoleReviewRoute
  '/_console/risk': typeof ConsoleRiskRoute
  '/_console/schedule': typeof ConsoleScheduleRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/time-agent': typeof ConsoleTimeAgentRoute
  '/_console/unmatched': typeof ConsoleUnmatchedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/conflicts'
    | '/cross-discipline'
    | '/dashboard'
    | '/extraction'
    | '/ingest'
    | '/matching'
    | '/memory'
    | '/project'
    | '/review'
    | '/risk'
    | '/schedule'
    | '/settings'
    | '/time-agent'
    | '/unmatched'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/conflicts'
    | '/cross-discipline'
    | '/dashboard'
    | '/extraction'
    | '/ingest'
    | '/matching'
    | '/memory'
    | '/project'
    | '/review'
    | '/risk'
    | '/schedule'
    | '/settings'
    | '/time-agent'
    | '/unmatched'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/_console/analytics'
    | '/_console/audit'
    | '/_console/conflicts'
    | '/_console/cross-discipline'
    | '/_console/dashboard'
    | '/_console/extraction'
    | '/_console/ingest'
    | '/_console/matching'
    | '/_console/memory'
    | '/_console/project'
    | '/_console/review'
    | '/_console/risk'
    | '/_console/schedule'
    | '/_console/settings'
    | '/_console/time-agent'
    | '/_console/unmatched'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/analytics': {
      id: '/_console/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ConsoleAnalyticsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/audit': {
      id: '/_console/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/conflicts': {
      id: '/_console/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConsoleConflictsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/cross-discipline': {
      id: '/_console/cross-discipline'
      path: '/cross-discipline'
      fullPath: '/cross-discipline'
      preLoaderRoute: typeof ConsoleCrossDisciplineRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/dashboard': {
      id: '/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/extraction': {
      id: '/_console/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ConsoleExtractionRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/ingest': {
      id: '/_console/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof ConsoleIngestRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/matching': {
      id: '/_console/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof ConsoleMatchingRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/memory': {
      id: '/_console/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof ConsoleMemoryRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/project': {
      id: '/_console/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ConsoleProjectRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/review': {
      id: '/_console/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ConsoleReviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/risk': {
      id: '/_console/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof ConsoleRiskRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/schedule': {
      id: '/_console/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ConsoleScheduleRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/time-agent': {
      id: '/_console/time-agent'
      path: '/time-agent'
      fullPath: '/time-agent'
      preLoaderRoute: typeof ConsoleTimeAgentRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/unmatched': {
      id: '/_console/unmatched'
      path: '/unmatched'
      fullPath: '/unmatched'
      preLoaderRoute: typeof ConsoleUnmatchedRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAnalyticsRoute: typeof ConsoleAnalyticsRoute
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleConflictsRoute: typeof ConsoleConflictsRoute
  ConsoleCrossDisciplineRoute: typeof ConsoleCrossDisciplineRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleExtractionRoute: typeof ConsoleExtractionRoute
  ConsoleIngestRoute: typeof ConsoleIngestRoute
  ConsoleMatchingRoute: typeof ConsoleMatchingRoute
  ConsoleMemoryRoute: typeof ConsoleMemoryRoute
  ConsoleProjectRoute: typeof ConsoleProjectRoute
  ConsoleReviewRoute: typeof ConsoleReviewRoute
  ConsoleRiskRoute: typeof ConsoleRiskRoute
  ConsoleScheduleRoute: typeof ConsoleScheduleRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleTimeAgentRoute: typeof ConsoleTimeAgentRoute
  ConsoleUnmatchedRoute: typeof ConsoleUnmatchedRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAnalyticsRoute: ConsoleAnalyticsRoute,
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleConflictsRoute: ConsoleConflictsRoute,
  ConsoleCrossDisciplineRoute: ConsoleCrossDisciplineRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleExtractionRoute: ConsoleExtractionRoute,
  ConsoleIngestRoute: ConsoleIngestRoute,
  ConsoleMatchingRoute: ConsoleMatchingRoute,
  ConsoleMemoryRoute: ConsoleMemoryRoute,
  ConsoleProjectRoute: ConsoleProjectRoute,
  ConsoleReviewRoute: ConsoleReviewRoute,
  ConsoleRiskRoute: ConsoleRiskRoute,
  ConsoleScheduleRoute: ConsoleScheduleRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleTimeAgentRoute: ConsoleTimeAgentRoute,
  ConsoleUnmatchedRoute: ConsoleUnmatchedRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
